[build-system]
requires = [
    "setuptools",
    "wheel",
    "setuptools-scm"
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "src/protontricks/_version.py"

[tool.coverage.report]
omit = [
  "*/protontricks/_vdf/*"
]
