[build-system]
requires = [
    "setuptools",
    "wheel",
    "setuptools-scm < 6 ; python_version <= '3.5'",
    "setuptools-scm ; python_version > '3.5'"
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "src/protontricks/_version.py"
